baseurl = "/"
title = "Darya Vanichkina"
googleAnalytics = "UA-54373354-1"
theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

disqusShortname = "dvanicw"

[params]
    author = "Darya Vanichkina PhD"
    description = "Darya Vanichkina's personal website"
    keywords = "data scientist, bioinformatician, consultant, educator"
    info = "Data Scientist & Professional Educator"
    avatarurl = "images/daryaVhead1.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = [ "static/css/custom.css"]
    
    # Ignore files
    ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
    
    # make ugly urls
    uglyURLs = true
    
[permalinks]
    post = "/posts/:slug/"

[taxonomies]
  series = "series"
  tags = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/dvanic"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab"
#    weight = 2 #change this to be 2 and renumber if uncommenting
#    url = "https://gitlab.com/dvanic"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/dvanichkina"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/daryavanichkina"

 [params.csp]
  childsrc = ["'self'"]
  fontsrc = ["'self'"]
  formaction = ["'self'"]
  framesrc = ["'self'"]
  imgsrc = ["'self'"]
  objectsrc = ["'none'"]
  stylesrc = ["'self'"]
  scriptsrc = ["'self'",
    "'unsafe-inline'",
    "https://platform.twitter.com",
    "*.amazon-adsystem.com",
    "https://www.google-analytics.com",
    "cse.google.com",
    "https://www.google.com",
    "https://pagead2.googlesyndication.com",
    "https://adservice.google.com",
    "https://www.googletagservices.com",
    "www.instagram.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com",
    "*.slideshare.net",
    "*.figshare.com",
    "*.youtube.com"
    ]


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Training"
        weight = 3
        url = "/training/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 5
        url = "/contact/"

[markup.goldmark.renderer]
unsafe= true
